--Considera Subsidios + Aportes desde tablas consolidadas
WITH TABLA_SUBSIDIOS AS (
Select DP.PRCN_ANO                   AS ANO, 
	   DP.PRCN_MES                   AS MES,
	   DP.DSPG_TIPO_PAGO             AS DSPG_TIPO_PAGO,
	   CON.ADHR_NUMERO               AS ADHR_NUMERO,
	   CON.ADHR_RAZON_SOCIAL         AS ADHR_RAZON_SOCIAL,
	   CON.HLDG_HOLDING              AS HLDG_HOLDING,
	   --DP.SNST_CODIGO_TIPO_ACCIDENTE AS TIPO_ACC,
	   SUM(DP.DSPG_MONTO)            AS MONTO
	   --,SUM(DSPG_DIAS)                AS DIAS
from SINIESTROS.DIAS_PAGADOS DP
LEFT JOIN SINIESTROS.CONTRATOS CON ON DP.ADHR_NUMERO = CON.ADHR_NUMERO
WHERE DSPG_TIPO_PAGO NOT LIKE '%REABONO%'
--DSPG_TIPO_PAGO = ''
--HLDG_ID IN ('H00006','H00154','H00115','H01021','H00931','H01518','H00260','H00234','H01772','H01509','H00039')
GROUP BY DP.PRCN_ANO,
	     DP.PRCN_MES,
	     DP.DSPG_TIPO_PAGO,
	     CON.ADHR_NUMERO,
	     CON.ADHR_RAZON_SOCIAL,
	     CON.HLDG_HOLDING
	     --,DP.SNST_CODIGO_TIPO_ACCIDENTE
--ORDER BY DP.PRCN_ANO DESC, DP.PRCN_MES DESC, SNST_CODIGO_TIPO_ACCIDENTE DESC
)

, 

TABLA_APORTES AS (
Select DP.PRCN_ANO                   AS ANO,
	   DP.PRCN_MES                   AS MES,
	   DP.DSPG_TIPO_PAGO             AS DSPG_TIPO_PAGO,
	   CON.ADHR_NUMERO               AS ADHR_NUMERO,
	   CON.ADHR_RAZON_SOCIAL         AS ADHR_RAZON_SOCIAL,
	   CON.HLDG_HOLDING              AS HLDG_HOLDING,
	   --DP.SNST_CODIGO_TIPO_ACCIDENTE AS TIPO_ACC,
	   SUM(DSPG_MONTO)               AS MONTO
	   --,SUM(DP.DSPG_DIAS)             AS DIAS
from DHUENUHUEQUE2.DH_DIAS_PAGADOS_APORTES DP
LEFT JOIN SINIESTROS.CONTRATOS CON ON DP.ADHR_NUMERO = CON.ADHR_NUMERO
WHERE DSPG_TIPO_PAGO = 'PAGO APORTE'
--AND --HLDG_NOMBRE = 'CENCOSUD'
--HLDG_ID IN ('H00006','H00154','H00115','H01021','H00931','H01518','H00260','H00234','H01772','H01509','H00039')
GROUP BY DP.PRCN_ANO, 
         DP.PRCN_MES,
         DP.DSPG_TIPO_PAGO,
	   	 CON.ADHR_NUMERO,              
	     CON.ADHR_RAZON_SOCIAL,
	     CON.HLDG_HOLDING       
         --,SNST_CODIGO_TIPO_ACCIDENTE
--ORDER BY DP.PRCN_ANO DESC, DP.PRCN_MES DESC, DP.SNST_CODIGO_TIPO_ACCIDENTE DESC

 )
 
SELECT * FROM TABLA_SUBSIDIOS
UNION ALL
SELECT * FROM TABLA_APORTES