SELECT PRCN_MES, SUM(CTZC_MASA) MASA, COUNT(DISTINCT ADHR_NUMERO) EMPRESAS
FROM SINIESTROS.COTIZACIONES_DISTRIBUIDAS CD
WHERE PRCN_ANO = 2025
GROUP BY PRCN_MES
ORDER BY 1

-------- Estos fueron LOS NUEVOS CAMBIOS--------